language: node_js
node_js:
  - v10
  - v8
before_install:
  # set up intermine
  - git clone https://github.com/intermine/testmine-ci.git
  - bash testmine-ci/init-testmine.sh
  # set up bluegenes
  - bash setup-bluegenes.sh

script:
  - ./ci/travis.sh
